const level1 = [
    {
        id:0,
        pick:null,
        row:'row1',
        col:'col1',
        vertical:'vertical1'
    },
    {
        id:1,
        pick:null,
        row:'row1',
        col:'col2'
    },
    {
        id:2,
        pick:null,
        row:'row1',
        col:'col3',
        vertical:'vertical2'
    },
    {
        id:3,
        pick:null,
        row:'row2',
        col:'col1'
    },
    {
        id:4,
        pick:null,
        row:'row2',
        col:'col2',
        vertical:'center'
    },
    {
        id:5,
        pick:null,
        row:'row2',
        col:'col3'
    },
    {
        id:6,
        pick:null,
        row:'row3',
        col:'col1',
        vertical:'vertical2'
    },
    {
        id:7,
        pick:null,
        row:'row3',
        col:'col2'
    },
    {
        id:8,
        pick:null,
        row:'row3',
        col:'col3',
        vertical:'vertical1'
    },
]
export default level1